"""empty message

Revision ID: 33c12dd6c4ef
Revises: None
Create Date: 2014-01-21 00:17:32.826556

"""

# revision identifiers, used by Alembic.
from sqlalchemy.sql import table

revision = '33c12dd6c4ef'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_name', sa.String(length=64), nullable=True),
        sa.Column('password', sa.String(length=320), nullable=True),
        sa.Column('role', sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_password', 'user', ['password'], unique=True)
    op.create_index('ix_user_user_name', 'user', ['user_name'], unique=True)
    ### end Alembic commands ###

    users_table = table('user',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user_name', sa.String(64), nullable=False, unique=True),
        sa.Column('password', sa.String(320)),
        sa.Column('role', sa.SmallInteger()),
    )

    op.bulk_insert(users_table,
        [
            {'id':1,
             'user_name':'redawn',
             'role':1,
             'password':'$6$rounds=106743$Aerhh6b4o0Vm/zN3$nPE1YpiarhEG/vCFzNJxgFqdGo3C.UUZR7VpV1B3G/BYMMMprNMvYZCBiaoZQMbvLXCP5i2uPy/6bhrSdSvqI.'}
        ]
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_user_name', 'user')
    op.drop_index('ix_user_password', 'user')
    op.drop_table('user')
    ### end Alembic commands ###
